Run main.py

Exit code references:
    0: No error
    1: Successfull Operation
    2: Invalid Input 
    4: First user, File not found